export { ReactComponent as Language } from './language.svg'
export { ReactComponent as Menu } from './menu.svg'
export { ReactComponent as MenuOpen } from './menu_open.svg'
export { ReactComponent as ViewDay } from './view_day.svg'
export { ReactComponent as ViewDayLine } from './view_day-line.svg'
