export const GET_INSTALL_FILE_FAILED = "GET_INSTALL_FILE_FAILED";
export const GET_CONFIG_FAILED = "GET_CONFIG_FAILED";
export const NOT_FOUND_CONFIG = "NOT_FOUND_CONFIG";
export const CONNECT_API_ERROR = "CONNECT_API_ERROR";
export const NOT_FOUND_ANY_ISSUES = "NOT_FOUND_ANY_ISSUES";
