export const GET_GIST_FILE_FAILED = "GET_GIST_FILE_FAILED";
export const GET_GIST_OPTION_FAILED = "GET_GIST_OPTION_FAILED";
export const GET_GIST_CONFIG_FAILED = "GET_GIST_CONFIG_FAILED";
export const GET_GIST_SETTINGS_FAILED = "GET_GIST_SETTINGS_FAILED";
export const GET_CONFIG_FAILED = "GET_CONFIG_FAILED";
export const NOT_FOUND_CONFIG = "NOT_FOUND_CONFIG";
export const CONNECT_API_ERROR = "CONNECT_API_ERROR";
export const NOT_FOUND_ANY_ISSUES = "NOT_FOUND_ANY_ISSUES";
